const $ = (id) => document.getElementById(id);
const icons = [
  { i: '⚔', n: 'DAGGER', v: 5 }, { i: '🛡', n: 'SHIELD', v: 0 },
  { i: '◈', n: 'COIN', v: 12 }, { i: '☠', n: 'POISON', v: 4 },
  { i: '✹', n: 'BOMB', v: 7 }, { i: '×2', n: 'MULTIPLIER', v: 2 },
  { i: '♜', n: 'JOKER', v: 3 }, { i: '✦', n: 'STAR', v: 2 }
];
const enemies = [['THE VAULT WARDEN', '☠', 80, 7, 2], ['IRON REVENANT', '♞', 105, 9, 3], ['THE LOCKED KING', '♛', 140, 12, 5]];
const saved = JSON.parse(localStorage.getItem('vaultMeta') || 'null') || { chips: 0, reels: 3 };
const state = { coins: 100, hp: 30, shield: 0, bosses: 0, round: 1, bet: 5, reels: saved.reels, enemy: enemies[0], enemyShield: 18, enemyHp: 80, spinning: false, stopped: 0, risk: false, forced: null };
const reelEls = [...document.querySelectorAll('.reel')];

function updateUI() {
  const enemy = state.enemy || enemies[state.bosses % enemies.length];
  $('coins').textContent = state.coins; $('chips').textContent = saved.chips; $('chipBank').textContent = saved.chips;
  $('playerHp').textContent = state.hp; $('playerShield').textContent = state.shield; $('round').textContent = String(state.round).padStart(2, '0'); $('run').textContent = String(state.round).padStart(2, '0'); $('bosses').textContent = state.bosses;
  $('reelCount').textContent = state.reels; $('poolCount').textContent = icons.length; $('enemyName').textContent = enemy[0]; $('enemyArt').textContent = enemy[1]; $('targetHpText').textContent = `${Math.max(0, state.enemyHp)} / ${enemy[2]}`;
  $('enemyHpBar').firstElementChild.style.width = `${Math.max(0, state.enemyHp / enemy[2] * 100)}%`; $('enemyShieldBar').firstElementChild.style.width = `${Math.max(0, state.enemyShield / 18 * 100)}%`;
  $('playerHpBar').style.width = `${Math.max(0, state.hp / 30 * 100)}%`; $('playerShieldBar').style.width = `${Math.min(100, state.shield / 30 * 100)}%`;
  $('intentDamage').textContent = `${enemy[3]} / ${enemy[4]}`; $('intentBoxDamage').textContent = `${enemy[3]}+${enemy[4]}`; $('intent').textContent = state.enemy ? 'HOSTILE INTENT' : 'WAITING FOR INPUT'; $('intentBox').textContent = enemy[3] > 9 ? 'HEAVY STRIKE' : 'LUNGE + HEX';
  $('strike').disabled = !state.enemy || state.spinning; $('guard').disabled = !state.enemy || state.spinning;
}
function note(message) { $('log').textContent = message; }
function toast(message) { const item = $('toast'); item.textContent = message; item.classList.add('show'); setTimeout(() => item.classList.remove('show'), 1700); }
function tone(frequency = 420) { try { const audio = new AudioContext(); const oscillator = audio.createOscillator(); const gain = audio.createGain(); oscillator.frequency.value = frequency; oscillator.type = 'square'; gain.gain.setValueAtTime(.025, audio.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audio.currentTime + .12); oscillator.connect(gain).connect(audio.destination); oscillator.start(); oscillator.stop(audio.currentTime + .12); } catch (error) {} }
function chooseIcon() { return state.forced ? state.forced.splice(0, 1)[0] : icons[Math.floor(Math.random() * icons.length)]; }
function startSpin() { if (state.spinning || state.coins < state.bet) return toast(state.coins < state.bet ? 'Insufficient gold.' : ''); state.coins -= state.bet; state.spinning = true; state.stopped = 0; reelEls.forEach((reel) => { reel.className = 'reel pulse'; reel.querySelector('small').textContent = 'SPINNING'; }); $('spin').textContent = 'STOP ACTIVE REEL'; $('phaseHint').textContent = 'STOP THE ACTIVE REEL · HIT GREEN FOR A CRIT'; $('turnLabel').textContent = 'STOP REELS'; updateUI(); tone(180); spinLoop(); }
function spinLoop() { if (!state.spinning) return; const active = reelEls[state.stopped]; if (active) active.querySelector('span').textContent = icons[Math.floor(Math.random() * icons.length)].i; setTimeout(spinLoop, 90); }
function stopReel() { if (!state.spinning) return; const reel = reelEls[state.stopped]; const result = chooseIcon(); reel.className = 'reel active'; reel.querySelector('span').textContent = result.i; reel.querySelector('small').textContent = result.n; reel.dataset.name = result.n; reel.dataset.value = result.v; state.stopped += 1; tone(360); if (state.stopped < state.reels) { reelEls[state.stopped].className = 'reel active'; return; } finishTurn(); }
function finishTurn() { state.spinning = false; $('spin').textContent = 'SPIN REELS'; $('turnLabel').textContent = 'ENEMY TURN'; reelEls.forEach((reel) => reel.classList.remove('active')); let damage = 0; let gold = 0; let shield = 0; let poison = 0; let bomb = 0; let multiplier = 1; reelEls.forEach((reel) => { const name = reel.dataset.name; const value = Number(reel.dataset.value); if (name === 'DAGGER') damage += value; if (name === 'COIN') gold += value; if (name === 'SHIELD') shield += 8; if (name === 'POISON') poison += value; if (name === 'BOMB') bomb += value; if (name === 'MULTIPLIER') multiplier *= 2; if (name === 'JOKER') multiplier *= 3; }); const names = reelEls.map((reel) => reel.dataset.name); if (names.every((name) => name === names[0])) { damage *= 3; gold += 20; note(`COMBO CRIT: TRIPLE ${names[0]} · x3 ACTION`); tone(780); } else note(`REELS LOCKED · ${damage} DAMAGE · ${gold} GOLD`); damage = damage * multiplier + bomb; state.coins += gold + Math.floor(Math.random() * 4); state.shield += shield; const blocked = Math.min(state.enemyShield, damage); state.enemyShield -= blocked; state.enemyHp -= damage - blocked + poison; if (state.risk) { state.coins += gold; note('RISK REWARD: GOLD DOUBLED'); state.risk = false; $('risk').classList.remove('on'); $('risk').querySelector('b').textContent = 'OFF'; } if (state.enemyHp <= 0) return winEnemy(); enemyTurn(); updateUI(); }
function enemyTurn() { const enemy = enemies[state.bosses % enemies.length]; state.shield = Math.max(0, state.shield - enemy[3]); state.hp -= enemy[4]; note(`${enemy[0]} attacks · ${enemy[3]} PHYSICAL / ${enemy[4]} ARCANE`); if (state.hp <= 0) gameOver(); setTimeout(() => $('turnLabel').textContent = 'YOUR TURN', 500); }
function winEnemy() { const enemy = enemies[state.bosses % enemies.length]; state.coins += 35 + state.bosses * 15; state.bosses += 1; state.enemy = enemies[state.bosses % enemies.length]; state.enemyHp = state.enemy[2]; state.enemyShield = 18; note(`${enemy[0]} DEFEATED · GOLD ERUPTS FROM THE VAULT`); toast('BOSS DEFEATED · +GOLD'); tone(900); updateUI(); }
function gameOver() { saved.chips += Math.max(1, Math.floor(state.bosses / 2) + 1); localStorage.setItem('vaultMeta', JSON.stringify(saved)); toast('RUN LOST · META-CHIP BANKED'); setTimeout(() => location.reload(), 1200); }
function buy(type, cost) { if (state.coins < cost) return toast('Not enough gold.'); state.coins -= cost; if (type === 'dagger') icons.push({ i: '⚔', n: 'DAGGER+', v: 8 }); if (type === 'shield') state.shield += 15; if (type === 'reel' && state.reels < 5) state.reels += 1; updateUI(); note(`PURCHASED ${type.toUpperCase()}`); }
$('spin').onclick = () => state.spinning ? stopReel() : startSpin(); $('risk').onclick = () => { state.risk = !state.risk; $('risk').classList.toggle('on', state.risk); $('risk').querySelector('b').textContent = state.risk ? 'ON' : 'OFF'; }; $('strike').onclick = () => { if (state.enemy) { state.enemyHp -= 8; state.enemyShield = Math.max(0, state.enemyShield - 4); enemyTurn(); updateUI(); } }; $('guard').onclick = () => { if (state.enemy) { state.shield += 10; enemyTurn(); updateUI(); } }; $('shopWeapon').onclick = () => buy('dagger', 35); $('shopShield').onclick = () => buy('shield', 25); $('shopReel').onclick = () => buy('reel', 80); document.onkeydown = (event) => { if (event.code === 'Space') state.spinning ? stopReel() : $('strike').click(); }; const dialog = $('dialog'); $('manual').onclick = () => dialog.showModal(); $('close').onclick = () => dialog.close(); $('sound').onclick = () => toast('SOUND TOGGLE READY'); updateUI();